version: 2.1

jobs:
  build-docker-image:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: 
            docker build -f Dockerfile.dev ./client

workflows:
  example-workflow:
    jobs:
      - build-docker-image
