version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  test-client:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - docker/check
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/build:
          image: client-test
          dockerfile: Dockerfile.dev 
          docker-context: client 
          path: client
          tag: latest
      - run:
          name: run test
          command: 
            docker run -e CI=true client-test npm run test
  build-docker-image:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Client Docker Image
          command: 
            docker build -t hoangnhdocker/multi-client:latest ./client
      - run:
          name: Build Server Docker Image
          command: 
            docker build -t hoangnhdocker/multi-server:latest ./server
      - run:
          name: Build Nginx Docker Image
          command: 
            docker build -t hoangnhdocker/multi-nginx:latest ./nginx
      - run:
          name: Build Worker Docker Image
          command: 
            docker build -t hoangnhdocker/multi-worker:latest ./worker
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push hoangnhdocker/multi-client:latest
            docker push hoangnhdocker/multi-server:latest
            docker push hoangnhdocker/multi-nginx:latest
            docker push hoangnhdocker/multi-worker:latest


workflows:
  example-workflow:
    jobs:
      - test-client
      - build-docker-image
