version: 2.1

jobs:
  build-docker-image:
    docker:
      # replace with your preferred image
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Client Docker Image
          command: 
            docker build -t hoangnhdocker/multi-client:latest ./client
      - run:
          name: Build Server Docker Image
          command: 
            docker build hoangnhdocker/multi-server:latest ./server
      - run:
          name: Build Nginx Docker Image
          command: 
            docker build hoangnhdocker/multi-nginx:latest ./nginx
      - run:
          name: Build Worker Docker Image
          command: 
            docker build hoangnhdocker/multi-worker:latest ./worker
            
workflows:
  example-workflow:
    jobs:
      - build-docker-image
